const fs=require('fs');
let h=fs.readFileSync('hdpatch2d.txt','utf8'); // готовый патч подписей (hdpatch2d.txt), здесь только сборка под Speedrun
const flag=fs.readFileSync('p-car0.js','utf8').match(/e\.innerHTML='(<svg.*?<\/svg>)'/)[1];
const card=String.raw` const o={rank:999,total:0,rival:{no:'#998',name:'Александр Константинов',val:'9:59'},ghost:{pid:1,cat:'speedrun',best:599},ratio:0.998,rivalSkin:0}; const elc=document.getElementById('overRank'); elc.innerHTML=overSaCardHtml(o); elc.classList.add('gcard'); elc.classList.remove('hidden'); overSaWorld(o); const cv=elc.querySelector('.gcSkin'); if(cv) overSkinDraw(cv,0); await new Promise(r=>setTimeout(r,500));`;
const flagJs=` document.querySelectorAll('.ofBox .ofStk[data-kind=finish]').forEach(e=>{ e.innerHTML='${flag}'; e.style.cssText+=';width:50px;height:50px;margin:-25px 0 0 -25px;border:3px solid #fff3c4;background:radial-gradient(circle at 35% 28%,#fff0b0,#f0b83a 70%);box-shadow:0 0 0 6px rgba(255,217,102,.18),0 0 22px rgba(255,217,102,.75);'; });`;
const tail=String.raw` await new Promise(r=>setTimeout(r,500)); clearInterval(window.__t); const R=s=>{const e=document.querySelector(s);if(!e||e.offsetParent===null)return null;const r=e.getBoundingClientRect();return [Math.round(r.top),Math.round(r.bottom)]}; const lb=document.getElementById('finalScoreLabel').getBoundingClientRect(), inf=document.querySelector('.ofInfo').getBoundingClientRect(); const rg=document.querySelector('#overFlight .hdL>span'); const rr=rg&&rg.offsetParent?rg.getBoundingClientRect():null; return 'слева=['+document.getElementById('finalScoreLabel').textContent+'] '+Math.round(lb.left)+'–'+Math.round(lb.right)+' (i с '+Math.round(inf.left)+')'+(rr?' справа=['+rg.textContent+'] '+Math.round(rr.left)+'–'+Math.round(rr.right):'')+' | окно '+R('#overFlight')+' карточка '+R('#overRank')+' кнопки '+R('#overRow'); })()`;
const goalJs=String.raw` const flg=document.getElementById('overFlight'); const cssG=document.createElement('style'); cssG.textContent='.goalFoot{margin:auto 16px 14px;padding-top:12px;border-top:1px solid rgba(255,122,61,.28)} .goalRow{display:flex;justify-content:space-between;font:800 12px/1 "Exo 2",sans-serif;letter-spacing:.1em;text-transform:uppercase;margin-bottom:8px;color:#b9c9e6} .goalRow b{color:#ffb27a} .goalBar{height:10px;border-radius:5px;background:rgba(255,255,255,.1);overflow:hidden} .goalBar i{display:block;height:100%;width:99.99%;background:linear-gradient(90deg,#ff7a3d,#ffb27a)}'; document.head.appendChild(cssG); const gf=document.createElement('div'); gf.className='goalFoot'; gf.innerHTML='<div class="goalRow"><span>Цель 10 000</span><b>Не хватило 1</b></div><div class="goalBar"><i></i></div>'; flg.appendChild(gf);`;
const mk=(win,k)=>'(async()=>{ await new Promise(r=>setTimeout(r,1300)); window.__cat=null; window.__nodist=true; window.__extra='+(win?"[{txt:'−60 с к рекорду',icon:'x',rec:true}]":"[]")+';\n'+(win?card:'')+'\n'+h.replace(/FRAME/g,String(k)).replace('const css2','const cssZ')+'\n'+(win?flagJs+" const fs0=document.getElementById('finalScore'); fs0.textContent=fs0.textContent.replace(/.0$/,'');":goalJs)+'\n'+tail;
for(const k of [1,2,3,4]) fs.writeFileSync('p-spw'+k+'.js',mk(true,k));
for(const k of [1,2]) fs.writeFileSync('p-spd'+k+'.js',mk(false,k));
console.log('ok');
