(async()=>{ await new Promise(r=>setTimeout(r,1300));
 document.getElementById('finalScore').textContent='1420'; document.querySelectorAll('.ofCap').forEach(e=>{ e.textContent=e.textContent.replace('9 000','1 420'); });
 overRankFill({ok:true,me:{rank:3,best:1420},top:[{pid:1,name:'Иван',best:1776},{pid:9,name:'Александр Константинов',best:1650},{me:true,best:1420}]},'caravan'); await new Promise(r=>setTimeout(r,900));
 const cssL=document.createElement('style'); cssL.textContent='.lbIc{display:inline-flex;width:14px;height:14px;vertical-align:-3px;margin-right:5px} .lbIc svg{width:14px;height:14px} #finalScoreLabel,#overFlight .hdL>span{transition:opacity .25s;display:block;max-width:132px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'; document.head.appendChild(cssL);
 const flh=document.getElementById('overFlight'); const rows=[...flh.querySelectorAll('.recRow')].filter(r=>!/призрак/i.test(r.textContent));
 const info=r=>({txt:((r.querySelector('em')?r.querySelector('em').textContent:'')+' '+r.querySelector('b span').textContent).trim().replace(/^Новый\s+/i,''),icon:r.querySelector('.recIc').innerHTML,rec:r.classList.contains('rec')});
 const recs=rows.filter(r=>r.classList.contains('rec')).map(info), calm=rows.filter(r=>!r.classList.contains('rec')).map(info);
 const rc0=flh.querySelector('.recCol'); if(rc0) rc0.remove();
 const hdL=flh.querySelector('.hdL'); const hasWorld=!!hdL && getComputedStyle(hdL).display!=='none';
 const leftEl=document.getElementById('finalScoreLabel'), rightEl=hasWorld?hdL.querySelector('span'):null;
 const mkSlot=(el,extra)=>{ if(!el||!extra.length) return null; const base={txt:el.textContent.trim(),icon:'',rec:null,col:getComputedStyle(el).color}; return {el,items:[base].concat(extra)}; };
 const slotsL=[mkSlot(leftEl, hasWorld?recs:recs.concat(calm)), mkSlot(rightEl, hasWorld?calm:[])].filter(Boolean);
 const paint=(s,k)=>{ const it=s.items[k%s.items.length]; s.el.textContent=it.txt; s.el.style.color=it.icon?(it.rec?'#ffe08a':'#9fd2f5'):it.col; s.el.style.fontSize=it.icon?'10px':''; s.el.style.letterSpacing=it.icon?'.1em':''; s.el.style.whiteSpace='nowrap'; };
 const draw=k=>slotsL.forEach(s=>paint(s,k));
 draw(0); let kk=0; window.__t=setInterval(()=>{ kk++; slotsL.forEach(s=>{ s.el.style.opacity=0; setTimeout(()=>{ paint(s,kk); s.el.style.opacity=1; },260); }); },2600);
 const bx=flh.querySelector('.ofBox'); if(typeof overSaPlace==='function') overSaPlace(bx);

 document.querySelectorAll('.ofBox .ofStk[data-kind=finish]').forEach(e=>{ e.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" style="width:30px;height:30px"><path d="M5.5 21V3" stroke="#3a2604" stroke-width="2.2" stroke-linecap="round" fill="none"/><path d="M6.5 4h13v10h-13z" fill="#fff"/><path d="M6.5 4h3.25v3.33H6.5zM13 4h3.25v3.33H13zM9.75 7.33H13v3.34H9.75zM16.25 7.33h3.25v3.34h-3.25zM6.5 10.67h3.25V14H6.5zM13 10.67h3.25V14H13z" fill="#3a2604"/></svg>'; e.style.cssText+=';width:50px;height:50px;margin:-25px 0 0 -25px;border:3px solid #fff3c4;background:radial-gradient(circle at 35% 28%,#fff0b0,#f0b83a 70%);box-shadow:0 0 0 6px rgba(255,217,102,.18),0 0 22px rgba(255,217,102,.75);'; });
 await new Promise(r=>setTimeout(r,500)); clearInterval(window.__t); const R=s=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect();return [Math.round(r.top),Math.round(r.bottom)]}; const lb=document.getElementById('finalScoreLabel').getBoundingClientRect(), sc=document.getElementById('finalScore').getBoundingClientRect(), inf=document.querySelector('.ofInfo').getBoundingClientRect(); const rg=document.querySelector('#overFlight .hdL>span'); const rr=rg?rg.getBoundingClientRect():null; return 'подпись=['+document.getElementById('finalScoreLabel').textContent+'] '+Math.round(lb.left)+'–'+Math.round(lb.right)+' (i с '+Math.round(inf.left)+')'+(rr?' справа=['+rg.textContent+'] '+Math.round(rr.left)+'–'+Math.round(rr.right):'')+' | шапка '+R('.orHead')+' окно '+R('#overFlight')+' карточка '+R('#overRank')+' кнопки '+R('#overRow'); })()