(async()=>{ await new Promise(r=>setTimeout(r,1300)); window.__cat=null; window.__nodist=true; window.__extra=[];

 const cssL=document.createElement('style'); cssL.textContent='.lbIc{display:inline-flex;width:14px;height:14px;vertical-align:-3px;margin-right:5px} .lbIc svg{width:14px;height:14px} #finalScoreLabel,#overFlight .hdL>span{transition:opacity .25s;display:block;max-width:132px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'; document.head.appendChild(cssL);
 const flh=document.getElementById('overFlight'); const rows=[...flh.querySelectorAll('.recRow')].filter(r=>!/призрак/i.test(r.textContent)&&!(window.__nodist&&/дистанц/i.test(r.textContent)));
 const uni=t=>/дистанц/i.test(t)?'Рекорд дистанции':(/времен/i.test(t)?'Рекорд времени':(/рекорд/i.test(t)?'Рекорд счёта':t)); const info=r=>({txt:uni(((r.querySelector('em')?r.querySelector('em').textContent:'')+' '+r.querySelector('b span').textContent).trim()),icon:r.querySelector('.recIc').innerHTML,rec:r.classList.contains('rec')});
 const recs=rows.filter(r=>r.classList.contains('rec')).map(info), calm=rows.filter(r=>!r.classList.contains('rec')).map(info);
 const rc0=flh.querySelector('.recCol'); if(rc0) rc0.remove();
 const hdL=flh.querySelector('.hdL'); const hasWorld=!!hdL && getComputedStyle(hdL).display!=='none';
 const leftEl=document.getElementById('finalScoreLabel'), rightEl=hasWorld?hdL.querySelector('span'):null;
 const mkSlot=(el,extra)=>{ if(!el||!extra.length) return null; const base={txt:el.textContent.trim(),icon:'',rec:null,col:getComputedStyle(el).color}; return {el,items:[base].concat(extra)}; };
 const slotsL=[mkSlot(leftEl, recs.concat(window.__extra||[]).concat(calm)), mkSlot(rightEl, (hasWorld&&window.__cat)?[{txt:window.__cat,icon:'c',rec:false}]:[])].filter(Boolean);
 const paint=(s,k)=>{ const it=s.items[k%s.items.length]; s.el.textContent=it.txt; s.el.style.color=it.icon?(it.rec?'#ffe08a':'#9fd2f5'):it.col; s.el.style.fontSize=it.icon?'10px':''; s.el.style.letterSpacing=it.icon?'.1em':''; s.el.style.whiteSpace='nowrap'; };
 const draw=k=>slotsL.forEach(s=>paint(s,k));
 draw(1); let kk=1; window.__t=setInterval(()=>{ kk++; slotsL.forEach(s=>{ s.el.style.opacity=0; setTimeout(()=>{ paint(s,kk); s.el.style.opacity=1; },260); }); },2600);
 const bx=flh.querySelector('.ofBox'); if(typeof overSaPlace==='function') overSaPlace(bx);

 const flg=document.getElementById('overFlight'); const cssG=document.createElement('style'); cssG.textContent='.goalFoot{margin:auto 16px 14px;padding-top:12px;border-top:1px solid rgba(255,122,61,.28)} .goalRow{display:flex;justify-content:space-between;font:800 12px/1 "Exo 2",sans-serif;letter-spacing:.1em;text-transform:uppercase;margin-bottom:8px;color:#b9c9e6} .goalRow b{color:#ffb27a} .goalBar{height:10px;border-radius:5px;background:rgba(255,255,255,.1);overflow:hidden} .goalBar i{display:block;height:100%;width:99.99%;background:linear-gradient(90deg,#ff7a3d,#ffb27a)}'; document.head.appendChild(cssG); const gf=document.createElement('div'); gf.className='goalFoot'; gf.innerHTML='<div class="goalRow"><span>Цель 10 000</span><b>Не хватило 1</b></div><div class="goalBar"><i></i></div>'; flg.appendChild(gf);
 await new Promise(r=>setTimeout(r,500)); clearInterval(window.__t); const R=s=>{const e=document.querySelector(s);if(!e||e.offsetParent===null)return null;const r=e.getBoundingClientRect();return [Math.round(r.top),Math.round(r.bottom)]}; const lb=document.getElementById('finalScoreLabel').getBoundingClientRect(), inf=document.querySelector('.ofInfo').getBoundingClientRect(); const rg=document.querySelector('#overFlight .hdL>span'); const rr=rg&&rg.offsetParent?rg.getBoundingClientRect():null; return 'слева=['+document.getElementById('finalScoreLabel').textContent+'] '+Math.round(lb.left)+'–'+Math.round(lb.right)+' (i с '+Math.round(inf.left)+')'+(rr?' справа=['+rg.textContent+'] '+Math.round(rr.left)+'–'+Math.round(rr.right):'')+' | окно '+R('#overFlight')+' карточка '+R('#overRank')+' кнопки '+R('#overRow'); })()